# Generated by Django 4.2.4 on 2023-10-15 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ("-date_created",)},
        ),
        migrations.AddField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(
                default="default.png",
                upload_to="pimages",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
